include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    file_names: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
